#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pysaml2
Version  : 5.0.0
Release  : 56
URL      : https://files.pythonhosted.org/packages/ad/ca/e34d35e2b79bbd2eca05a9e4386545c1762715fe77488e83d9f09e73be07/pysaml2-5.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ad/ca/e34d35e2b79bbd2eca05a9e4386545c1762715fe77488e83d9f09e73be07/pysaml2-5.0.0.tar.gz
Summary  : Python implementation of SAML Version 2 Standard
Group    : Development/Tools
License  : Apache-2.0
Requires: pysaml2-bin = %{version}-%{release}
Requires: pysaml2-license = %{version}-%{release}
Requires: pysaml2-python = %{version}-%{release}
Requires: pysaml2-python3 = %{version}-%{release}
Requires: Paste
Requires: cryptography
Requires: defusedxml
Requires: pyOpenSSL
Requires: python-dateutil
Requires: pytz
Requires: repoze.who
Requires: requests
Requires: six
Requires: zope.interface
BuildRequires : Mako
BuildRequires : MarkupSafe-python
BuildRequires : Paste
BuildRequires : WebOb-python
BuildRequires : buildreq-distutils3
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : cryptography
BuildRequires : decorator-python
BuildRequires : defusedxml
BuildRequires : idna-python
BuildRequires : ipaddress-python
BuildRequires : mongodict
BuildRequires : py-python
BuildRequires : pyOpenSSL
BuildRequires : pyOpenSSL-python
BuildRequires : pyasn1-python
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pycrypto-python
BuildRequires : pymongo-python
BuildRequires : pytest-python
BuildRequires : python-dateutil
BuildRequires : python-dateutil-python
BuildRequires : python-memcached
BuildRequires : pytz
BuildRequires : pytz-python
BuildRequires : repoze.who
BuildRequires : repoze.who-python
BuildRequires : requests
BuildRequires : requests-python
BuildRequires : six
BuildRequires : six-python
BuildRequires : xmlsec1
BuildRequires : xmlsec1-dev
BuildRequires : zope.interface
BuildRequires : zope.interface-python

%description
*************************
PySAML2 - SAML2 in Python
*************************

:Version: see VERSION_
:Documentation: https://pysaml2.readthedocs.io/

.. image:: https://api.travis-ci.org/IdentityPython/pysaml2.png?branch=master
    :target: https://travis-ci.org/IdentityPython/pysaml2

.. image:: https://img.shields.io/pypi/pyversions/pysaml2.svg
    :target: https://pypi.org/project/pysaml2/

.. image:: https://img.shields.io/pypi/v/pysaml2.svg
    :target: https://pypi.org/project/pysaml2/


PySAML2 is a pure python implementation of SAML Version 2 Standard. It contains
all necessary pieces for building a SAML2 service provider or an identity
provider. The distribution contains examples of both. Originally written to
work in a WSGI environment there are extensions that allow you to use it with
other frameworks.

Install
=======
You can install with `pip install pysaml2`

Testing
=======

PySAML2 uses the pytest_ framework for testing. To run the tests on your
system's version of python:

1. Create and activate a virtualenv_
2. Inside the virtualenv_, install the dependencies needed for testing
   :code:`pip install -r tests/test-requirements.txt`
3. Run the tests :code:`py.test tests`

To run tests in multiple python environments, you can use pyenv_ with tox_.


Please contribute!
==================

To help out, you could:

1. Test and report any bugs or other difficulties.
2. Implement missing features.
3. Write more unit tests.

**If you have the time and inclination I'm looking for Collaborators**


.. _VERSION: VERSION
.. _pytest: https://docs.pytest.org/en/latest/
.. _virtualenv: https://virtualenv.pypa.io/en/stable/
.. _pyenv: https://github.com/yyuu/pyenv
.. _tox: https://tox.readthedocs.io/en/latest/

%package bin
Summary: bin components for the pysaml2 package.
Group: Binaries
Requires: pysaml2-license = %{version}-%{release}

%description bin
bin components for the pysaml2 package.


%package license
Summary: license components for the pysaml2 package.
Group: Default

%description license
license components for the pysaml2 package.


%package python
Summary: python components for the pysaml2 package.
Group: Default
Requires: pysaml2-python3 = %{version}-%{release}

%description python
python components for the pysaml2 package.


%package python3
Summary: python3 components for the pysaml2 package.
Group: Default
Requires: python3-core
Provides: pypi(pysaml2)

%description python3
python3 components for the pysaml2 package.


%prep
%setup -q -n pysaml2-5.0.0
cd %{_builddir}/pysaml2-5.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583209448
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pysaml2
cp %{_builddir}/pysaml2-5.0.0/LICENSE %{buildroot}/usr/share/package-licenses/pysaml2/be8f3eb13b3dfb0e413a47009022c3c5897b60e8
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/make_metadata.py
/usr/bin/mdexport.py
/usr/bin/merge_metadata.py
/usr/bin/parse_xsd2.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pysaml2/be8f3eb13b3dfb0e413a47009022c3c5897b60e8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
