#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pysaml2
Version  : 2.4.0
Release  : 15
URL      : https://pypi.python.org/packages/source/p/pysaml2/pysaml2-2.4.0.tar.gz
Source0  : https://pypi.python.org/packages/source/p/pysaml2/pysaml2-2.4.0.tar.gz
Summary  : Python implementation of SAML Version 2
Group    : Development/Tools
License  : Apache-2.0
Requires: pysaml2-bin
Requires: pysaml2-python
BuildRequires : Mako
BuildRequires : MarkupSafe-python
BuildRequires : WebOb-python
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : cryptography
BuildRequires : decorator-python
BuildRequires : enum34-python
BuildRequires : idna-python
BuildRequires : ipaddress-python
BuildRequires : mongodict
BuildRequires : paste-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py-python
BuildRequires : pyOpenSSL-python
BuildRequires : pyasn1-python
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pycrypto-python
BuildRequires : pymongo-python
BuildRequires : pytest-python
BuildRequires : python-dateutil-python
BuildRequires : python-dev
BuildRequires : python-memcached
BuildRequires : pytz-python
BuildRequires : repoze.who-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : xmlsec1
BuildRequires : xmlsec1-dev
BuildRequires : zope.interface-python
Patch1: drop-py2.6.patch
Patch2: test.patch

%description
==================
Dependencies
------------
PySAML2 should be compatible with any python >= 2.6 not 3.X yet.

%package bin
Summary: bin components for the pysaml2 package.
Group: Binaries

%description bin
bin components for the pysaml2 package.


%package python
Summary: python components for the pysaml2 package.
Group: Default

%description python
python components for the pysaml2 package.


%prep
%setup -q -n pysaml2-2.4.0
%patch1 -p1
%patch2 -p1

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/make_metadata.py
/usr/bin/mdexport.py
/usr/bin/merge_metadata.py
/usr/bin/parse_xsd2.py

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
